# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17qHmFbCe5FUr8G-ILH7S1pnDsDCGSgfV
"""

import pandas as pd

#Data
df = pd.read_csv("DatasetJugadoresAsobal.csv", sep=';', encoding="ISO-8859-1")
df.head()