# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17qHmFbCe5FUr8G-ILH7S1pnDsDCGSgfV
"""

import streamlit as st
import pandas as pd
import numpy as np

st.title('Uber pickups in NYC')

streamlit run app.py